config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls"), name="tube"),
]

tube/urls.py
from django.urls import path
from . import views

app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    #TIPS:<型:変数名>とすることでビューに変数を与えることができる

    path('delete/<int:pk>', views.delete, name="delete"),
    path('update/<int:pk>', views.update, name="update"),
]

tube/models.py
from django.db import models
from django.utils import timezone

class Video(models.Model):

    class Meta:

        db_table = "video"

    title   = models.CharField(verbose_name="タイトル", max_length=30)
    comment = models.CharField(verbose_name="動画説明文", max_length=2000)
    dt      = models.DateTimeField(verbose_name="投稿日", default=timezone.now)

    def __str__(self):
        return self.title

tube/forms.py
from django import forms 
from .models import Video


class VideoForm(forms.ModelForm):
    class Meta:
        model   = Video
        fields  = [ "title","comment", ]

tube/views.py
from django.shortcuts import render, redirect

from django.views import View
from .models import Video
from .forms import VideoForm


from django.db.models import Q

class IndexView(View):

    def get(self, request, *args, **kwargs):

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("tube:index")


            search = request.GET["search"].replace("　", " ")
            search_list = search.split(" ")


            query = Q()
            for word in search_list:

                if "option" in request.GET:
                    query |= Q(comment__contains=word)
                else:
                    query &= Q(comment__contains=word)


            videos = Video.objects.filter(query).order_by("-dt")
        else:
            videos = Video.objects.all().order_by("-dt")


        context = {"videos": videos}



        return render(request, "tube/index.html", context)

    def post(self, request, *args, **kwargs):

        """
        if "title" in request.POST:

            if request.POST["title"] == "" or request.POST["title"].isspace():
                return redirect("tube:index")

        if "comment" in request.POST:

            if request.POST["comment"] == "" or request.POST["comment"].isspace():
                return redirect("tube:index")

        posted = Video( title = request.POST["title"], comment = request.POST["comment"])
        posted.save()

        """
        
        formset = VideoForm(request.POST)

        if formset.is_valid():
            print("バリデーションOK")
            formset.save()
        else:
            print("バリデーションエラー")



        return redirect("tube:index")

index = IndexView.as_view()


class DeleteView(View):

    def post(self, request, pk, *args, **kwargs):

        print("削除")

        #.first()で一番上のレコードを1つ取る。
        video   = Video.objects.filter(id=pk).first()
        video.delete()

        #TIPS:すでにurls.pyにてpkが数値型であることがわかっているので、バリデーションをする必要はない。

        return redirect("tube:index")

delete  = DeleteView.as_view()

class UpdateView(View):
    
    def get(self, request, pk,*args, **kwargs):

        video   = Video.objects.filter(id=pk).first()
        context = { "video":video }

        return render(request, "tube/update.html", context )

    def post(self, request, pk, *args, **kwargs):

        #まず、編集対象のレコードを特定
        instance    = Video.objects.filter(id=pk).first()

        #第二引数にinstanceを指定することで、対象の編集ができる
        formset     = VideoForm(request.POST, instance=instance)

        if formset.is_valid():
            print("バリデーションOK")
            formset.save()
        else:
            print("バリデーションNG")

        return redirect("tube:index")

update  = UpdateView.as_view()

templates/common/sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block site_title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>


    <!--静的ファイルの読み込みは html冒頭でload staticのテンプレートタグを記述した後、下記のように読み込み指定する。-->
    <link rel="stylesheet" href="{% static 'common/css/style.css' %}">

    {% block extra_head %}
    {% endblock %}

</head>
<body>

    <header>
        <h1>{% block page_title %}{% endblock %}</h1>
    </header>


    <main>
    {% block main %}
    {% endblock %}
    </main>



</body>
</html>



templates/tube/index.html
{% extends "common/sidebar.html" %}


{% block site_title %}サイトのタイトル{% endblock %}


{% block extra_head %}
<script>console.log("追加のcssやjsがあればここにまとめて書く");</script>
{% endblock %}



{% block page_title %}{% endblock %}

{% block main %}
<main class="container">

        <form method="GET">
            <div>OR検索はチェックを入れる:<input type="checkbox" name="option" {% if request.GET.option %}checked{% endif %}></div>
            <input type="text" name="search" value="{{ request.GET.search }}">
            <input type="submit" value="検索">
        </form>



    <form method="POST">
        {% csrf_token %}

        
        <div><input class = "form-text" placeholder="タイトル..." name="title" value="{{ request.POST.title }}"></div>

        <div><textarea class="form-control" name="comment" placeholder="概要欄..." value="{{ request.POST.comment }}"></textarea></div>
        <input type="submit" value="送信">

    </form>
      {% for video in videos %}
    <div class="border">
        <div>{{ video.id }}</div>
        <div>{{ video.title }}</div>
        <div>{{ video.dt }}</div>
        <div>{{ video.comment }}</div>


        <!--TIPS:urlテンプレートタグの逆引き時に引数が必要な場合、半角スペースひとつ開けた後、適宜引数を与える-->
        <form action="{% url 'tube:delete' video.id %}" method="POST" style="display:inline-block;">
            {% csrf_token %}
            <button class="btn btn-danger">削除</button>
        </form>

        <a class="btn btn-success" href="{% url 'tube:update' video.id  %}">編集</a>

    </div>
      {% endfor %}
</main>
{% endblock %}




<!--TIPS:DTLのコメントアウトは{# #}で 

    {# videos #}
-->

<!--&lt;!&ndash;ユーザーがログイン済みの場合、userのis_authenticated属性値で判定できる。&ndash;&gt;-->
<!--  {% if user.is_authenticated %}-->
<!--  <div>こんにちは{{ user.get_username }}さん</div>-->
<!--  {% else%}-->
<!--  <div>ログインしてください</div>-->
<!--  {% endif %}-->



templates/tube/update.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>編集</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

    <form method="POST">
        {% csrf_token %}

        <div><input class = "form-text" placeholder="タイトル..." name="title" value="{{ video.title }}"></div>
        <!--TIPS:textarea属性にvalue属性は存在しない、中のタグに値を入れる。-->
        <div><textarea class="form-control" name="comment" placeholder="概要欄...">{{ video.comment }}</textarea></div>

        <input type="submit" value="送信">

    </form>



</body>
</html>